---
# - name: Setup Kubernetes
#   hosts: all
#   become: yes
#   roles:
#     - role: '../roles/kubernetes'
#     - role: '../roles/helm'


# - name: Setup Kubernetes Workers
#   hosts: workers
#   become: yes
#   roles:
#     - role: '../roles/join_kubernetes'


- name: Setup Kubernetes cluster
  hosts: masters
  become: yes
  roles: 
    # - role: '../roles/helm'
    # - role: '../roles/traefik'
    # - role: '../roles/zalando-postgres-op'
    # - role: '../roles/metallb'
    # - role: '../roles/longhorn'
    # - role: '../roles/falco'
    # - role: '../roles/docker-registry'
    # - role: '../roles/monitoring'
    # - role: '../roles/frontend'
    # - role: '../roles/backend'
    - role: '../roles/github-action'
    - role: '../roles/cartostage/backend'
    - role: '../roles/cartostage/frontend'
  vars_files:
    - ../group_vars/all/vault.yml
    
