---
- name: Créer le workspace backend
  file:
    path: "{{ workspace_path }}/backend"
    state: directory
    mode: '0755'

- name: Créer le namespace backend s'il n'existe pas
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: backend

- name: Copy postgres Manifest
  copy:
    src: "postgres.yaml"
    dest: "{{ workspace_path }}/backend/postgres.yaml"

- name: Copy configmap Manifest
  copy:
    src: "configmap.yaml"
    dest: "{{ workspace_path }}/backend/configmap.yaml"

- name: Copy deployment Manifest
  copy:
    src: "deployment.yaml"
    dest: "{{ workspace_path }}/backend/deployment.yaml"

- name: Copy IngressRoute Manifest
  copy:
    src: "ingressroute.yaml"
    dest: "{{ workspace_path }}/backend/ingressroute.yaml"


- name: Déployer PostgreSQL d'abord
  shell: |
    kubectl apply -f "{{ workspace_path }}/backend/postgres.yaml"

- name: Déployer le configmap
  shell: |
    kubectl apply -f "{{ workspace_path }}/backend/configmap.yaml"

- name: Déployer le deployment
  shell: |
    kubectl apply -f "{{ workspace_path }}/backend/deployment.yaml"
    
- name: Déployer l'ingressroute
  shell: |
    kubectl apply -f "{{ workspace_path }}/backend/ingressroute.yaml"

- name: Supprimer le workspace backend
  file:
    path: "{{ workspace_path }}/backend"
    state: absent
