version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: "192.168.1.11:8080"
