# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: mon-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: MysterNathan/vitrine
      env:
        - name: RUNNER_GROUP
          value: "Default"
        - name: RUNNER_LABELS
          value: "k8s,self-hosted"
