---
- name: Check if swap is enabled
  command: free -m
  register: free_output
  changed_when: false

- name: Disable Swap
  command: swapoff -a
  # when: "'Swap' in free_output.stdout"

- name: Remove swap entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#]+\s+swap\s+'
    state: absent
  register: fstab_updated

- name: Ensure swap is not listed in /etc/fstab
  command: mount -a
  when: fstab_updated.changed