- name: Installing APT requirered packages
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    update_cache: yes

- name: Add Kubernetes APT repository key
  become: yes
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository to sources.list.d
  become: yes
  ansible.builtin.shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list

- name: Installing Kubernetes packages
  ansible.builtin.apt:
    name:
    - kubelet 
    - kubeadm 
    - kubectl
    - gpg
    update_cache: yes

- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl


- name: Download containerd archive
  ansible.builtin.get_url:
    url: "https://github.com/containerd/containerd/releases/download/v1.7.13/containerd-1.7.13-linux-amd64.tar.gz"
    dest: "/tmp/containerd.tar.gz"
    mode: '0644'

- name: Extract containerd binary
  ansible.builtin.unarchive:
    src: "/tmp/containerd.tar.gz"
    dest: "/usr/local"
    remote_src: yes

- name: Download containerd systemd service file
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: "/etc/systemd/system/containerd.service"
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started

- name: Create containerd configuration directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd configuration
  ansible.builtin.command:
    cmd: containerd config default
  register: containerd_default_config

- name: Write containerd configuration file
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_config.stdout }}"
    mode: '0644'

- name: Enable SystemdCgroup in containerd configuration
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart and enable containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Download runc binary
  ansible.builtin.get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v1.1.11/runc.amd64"
    dest: "/usr/local/sbin/runc"
    mode: '0755'

- name: Download CNI plugins
  ansible.builtin.get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
    dest: "/tmp/cni-plugins.tgz"
    mode: '0644'

- name: Extract CNI plugins
  ansible.builtin.unarchive:
    src: "/tmp/cni-plugins.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes