# roles/k8s-backend/defaults/main.yaml
---
# Configuration par défaut
workspace_path: "/tmp/k8s-frontend-workspace"
backend_namespace: "frontend"
backend_manifests_source: "frontend/k8s-manifests.yaml"

