api:
  insecure: true
  dashboard: true

deployment:
  hostAliases:
  - ip: "192.168.100.10"
    hostnames:
     - "mysternathan.freeboxos.fr"

additionalArguments:
  - "--api.dashboard=true" 
  - "--providers.kubernetesingress"

ingressRoute:
  dashboard:
    enabled: true
