---
- name: Créer le namespace docker-registry s'il n'existe pas
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: docker-registry
    state: present

- name: Copier le fichier de déploiement pour la registry
  copy:
    src: deployment.yaml
    dest: /tmp/registry-deployment.yaml
    
- name: Appliquer le déploiement de la registry
  kubernetes.core.k8s:
    src: /tmp/registry-deployment.yaml
    state: present

- name: Configurer le fichier daemon.json pour activer l'insecure registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries" : ["192.168.1.193:30530"]
      }

- name: Vérifier le NodePort attribué à la registry
  shell: |
    kubectl get svc docker-registry -n docker-registry -o jsonpath='{.spec.ports[0].nodePort}'
  register: registry_nodeport

- name: Afficher le port d'accès à la registry
  debug:
    msg: "La registry est disponible sur http://192.168.1.193:{{ registry_nodeport.stdout }}"

- name: Copier le fichier daemonset.yaml sur la cible
  copy:
    src: daemonset.yaml
    dest: /tmp/daemonset.yaml

- name: Appliquer le DaemonSet
  shell: |
    kubectl apply -f /tmp/daemonset.yaml
  args:
    executable: /bin/bash