- name: Disable Swap
  include_tasks: disable_swap.yaml

- name: Configure iptables
  include_tasks: configure_iptables.yaml

- name: Install required packages
  include_tasks: install_packages.yaml

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

# Only executed on master
- name: Setup Kubernetes
  include_tasks: setup_k8s.yaml
  when: "'masters' in group_names"