---
- name: Créer le namespace docker-registry s'il n'existe pas
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: docker-registry
    state: present

- name: Créer le secret htpasswd pour la registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: registry-htpasswd
        namespace: docker-registry
      type: Opaque
      stringData:
        htpasswd: "{{ registry_htpasswd_password }}"

- name: Copier le fichier de déploiement pour la registry
  copy:
    src: deployment.yaml
    dest: /tmp/registry-deployment.yaml

- name: Creer le secret docker-registry pour la registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: registry-credentials
        namespace: "{{ item }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ {'auths': {'mysternathan.freeboxos.fr': {'username': registry_user, 'password': registry_password, 'auth': (registry_user + ':' + registry_password) | b64encode}}} | to_json | b64encode }}"
  loop:
    - csback
    - csfront


- name: Appliquer le déploiement de la registry
  kubernetes.core.k8s:
    src: /tmp/registry-deployment.yaml
    state: present

