---
- name: Créer le namespace Traefik
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: traefik
    state: present

- name: Add Traefik Helm repository
  ansible.builtin.command: helm repo add traefik https://traefik.github.io/charts
  changed_when: false

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Load values.yaml content
  copy:
    content: "{{ lookup('file', 'values.yaml') }}"
    dest: "/tmp/traefik-values.yaml"
  register: traefik_values_copy

- name: Install Traefik using the official method
  ansible.builtin.command: >
    helm upgrade --install --namespace=traefik traefik traefik/traefik -f /tmp/traefik-values.yaml
  register: traefik_install
  changed_when: traefik_install.rc == 0

- name: Install Traefik CRD 
  ansible.builtin.command: >
    kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.4/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  changed_when: traefik_install.rc == 0

- name: Install Traefik RBAC 
  ansible.builtin.command: >
    kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.4/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  changed_when: traefik_install.rc == 0

- name: Wait for IngressRoute CRD to be available
  ansible.builtin.shell: kubectl get crd ingressroutes.traefik.io
  register: crd_check
  until: crd_check.rc == 0
  retries: 12
  delay: 10
  changed_when: false

# Vérification des CRDs installées
- name: Verify Traefik CRDs are installed
  ansible.builtin.shell: kubectl get crds | grep traefik
  register: traefik_crds
  changed_when: false

- name: Display installed CRDs
  ansible.builtin.debug:
    var: traefik_crds.stdout_lines

# Vérifier l'API disponible pour modifier vos fichiers YAML si nécessaire
- name: Check available Traefik API
  ansible.builtin.shell: kubectl api-resources | grep traefik
  register: traefik_api
  changed_when: false

- name: Display Traefik API
  ansible.builtin.debug:
    var: traefik_api.stdout_lines

# Vérifier les pods Traefik pour confirmer le déploiement
- name: Check Traefik pods
  ansible.builtin.shell: kubectl get pods -n traefik
  register: traefik_pods
  changed_when: false

- name: Display Traefik pods
  ansible.builtin.debug:
    var: traefik_pods.stdout_lines

# Déploiement du secret d'authentification
- name: Copy Traefik auth-secret manifest
  copy:
    src: '{{ role_path }}/files/auth-secret.yaml'
    dest: /tmp/auth-secret.yaml

- name: Apply Traefik auth-secret
  command: kubectl apply -f /tmp/auth-secret.yaml

# Déploiement du middleware d'authentification
- name: Copy Traefik auth-middleware manifest
  copy:
    src: '{{ role_path }}/files/auth-middleware.yaml'
    dest: /tmp/auth-middleware.yaml

- name: Apply Traefik auth-middleware
  command: kubectl apply -f /tmp/auth-middleware.yaml


- name: Copy Traefik ingressroute manifest
  copy:
    src: '{{ role_path }}/files/ingressroute.yaml'
    dest: /tmp/traefikingressroute.yaml

- name: Expose Traefik dashboard
  command: kubectl apply -f /tmp/traefikingressroute.yaml