- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ github_runner_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy runner
  kubernetes.core.k8s:
    state: present
    template: runner.yaml.j2
